FROM joamatab/gdsfactory
USER root

RUN apt update
RUN apt install -y mosquitto

USER jovyan
RUN mamba install -y paho-mqtt flask

COPY --chown=jovyan klive_translator.py /usr/local/bin/
COPY --chown=jovyan --chmod=777 controler.sh /usr/local/bin/
