FROM joamatab/gdsfactory
COPY --chown=jovyan klive_translator.py /usr/local/bin/
COPY --chown=jovyan controler.sh /usr/local/bin/
USER root

RUN apt update
RUN apt install -y mosquitto

USER jovyan
RUN mamba install -y paho-mqtt flask

