FROM jadafi/gdsfactory_minimal

RUN apt update
RUN apt install -y mosquitto

RUN conda install -y paho-mqtt flask

COPY klive_translator.py /usr/local/bin/
COPY controler.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/controler.sh
